version: '3.8'

services:
  app:
    image: timotejekart/rgisvaja6:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=Izleti;User=sa;Password=YourPassword123.;"
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourPassword123."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./:/var/opt/mssql/data

volumes:
  db-data: