version: '3.8'
services:
  app:
    image: timotejekart/rgisvaja6:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Database=Izleti;User=sa;Password=Rgis;"
    depends_on:
      - db
    ports:
      - "7017:80"

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Rgis"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - izleti-db:/var/opt/mssql

volumes:
  izleti-db: